# Commit Message Best Practices

# A short single line summary (less than 50 characters) of the change you're making
# Optionally followed by a blank line and a more complete description
# Keep each line to less than 72 characters
# Write commit messages in the imperative: "Fix bug" and not "Fixed bug" or "Fixes bug." This convention matches up with commit messages generated by commands like git merge and git revert.
# Bullet points are usually asterisks or hyphens
# Can add a ticket or issue number
# Can develop a consistent format for commit messages
# Be clear and descriptive

# Example:

# #42 - Add a new command
# When an admin logged out and logged back in, they were redirected to the home page. This commit fixes the redirection bug by adding a new command to the admin controller.